Repository KyleMcMullin/CS3450-Group7, pull requests merged in 2022-10, with the labels that each got.

#96 84 kyle sign up database
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/SignTextInput.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/User.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SignUpScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SignUpViewModel.kt
Labels: bug, enhancement

#97 Burndown Chart Sprint 1 & 2
  docs/burndown-chart-sprint2.pdf
Labels: documentation

#124 47 kyle scaffold composable
  androidapp/DansFrappesRaps/app/build.gradle
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/RootNavigationViewModel.kt
Labels: enhancement

#129 splash screen and auto login
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/SplashScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/SplashScreenViewModel.kt
Labels: enhancement

#130 113 create menuitem component
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/MenuItem.kt
  androidapp/DansFrappesRaps/app/src/main/res/drawable/emptyimage.xml
Labels: enhancement

#133 Add floating action button
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
Labels: enhancement

#141 140 kyle manage users
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/UserListItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/User.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EditUserScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ManageUsersScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditUserViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/ManageUsersViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/util/userFilterText.kt
Labels: enhancement

#142 118 kyle manage inventory
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/InventoryItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/LabelledTextInput.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Inventory.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/InventoryRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/AdjustInventoryScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ManageInventoryScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ManageUsersScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/AdjustInventoryViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/ManageInventoryViewModel.kt
Labels: enhancement

#138 order item ui
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/OrderItem.kt
Labels: enhancement

#148 loader image with logo
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/Loader.kt
  androidapp/DansFrappesRaps/app/src/main/res/drawable/logo.png
Labels: enhancement

#150 122 kyle manage menu
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/DrinkItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/IngredientItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Drink.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Ingredient.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/DrinksRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/IngredientsRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/InventoryRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EditMenuScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ManageMenuScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditMenuViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/ManageMenuViewModel.kt
Labels: enhancement

#157 Adding item type to inventories
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/InventoryItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/models/Inventory.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/IngredientsRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/InventoryRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/AdjustInventoryScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/AdjustInventoryViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditMenuViewModel.kt
Labels: enhancement

#165 Payroll functionality
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/ManagePayrollItem.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/RootNavigation.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/navigation/Routes.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/repositories/UserRepository.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/DetailMenuScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EditUserScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/EmployeePayrollScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/screens/ManagePayrollScreen.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EditUserViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/EmployeePayrollViewModel.kt
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/viewmodels/ManagePayrollViewModel.kt
Labels: enhancement

#176 Making item auto close
  androidapp/DansFrappesRaps/app/src/main/java/com/cs3450/dansfrappesraps/ui/components/ManagePayrollItem.kt
Labels: bug, enhancement
